apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: cve-2024-21626
spec:
  kprobes:
  - call: "sys_chdir"
    syscall: true
    message: "CVE-2024-21626: Detected chdir to leaked file descriptor"
    args:
    - index: 0
      type: "string"
    selectors:
    - matchArgs:
      - index: 0
        operator: "Prefix"
        values: ["/proc/"]
      - index: 0
        operator: "Postfix"
        values: ["/fd/6", "/fd/7", "/fd/8"]
      matchBinaries:
      - operator: "Postfix"
        values: ["/runc"]
      matchActions:
      - action: Post
      - action: Override
        argError: -13  # -EPERM
