apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: cve-2025-31133
spec:
  kprobes:
  - call: "sys_openat"
    syscall: true
    message: "CVE-2025-31133: Blocked write to core_pattern"
    args:
    - index: 0
      type: "int"
    - index: 1
      type: "string"
    - index: 2
      type: "int"
    selectors:
    - matchArgs:
      - index: 1
        operator: "Equal"
        values: ["/proc/sys/kernel/core_pattern"]
      - index: 2
        operator: "Mask"
        values: ["0x1", "0x2"]  # [O_WRONLY, O_RDWR]
      matchNamespaces:
      - namespace: Mnt
        operator: NotIn
        values: ["host_ns"]
      matchActions:
      - action: Post
      - action: Override
        argError: -13  # -EPERM
